CREATE TABLE IF NOT EXISTS member(
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        email VARCHAR(256) NOT NULL UNIQUE,
                        age INTEGER
);

CREATE TABLE IF NOT EXISTS Article(
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         title VARCHAR(256) NOT NULL,
                         description TEXT,
                         created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         member_id INTEGER NOT NULL,
                         CONSTRAINT fk_article_member
                             FOREIGN KEY (member_id)
                                 REFERENCES member(id)
                                 ON DELETE CASCADE
);